version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.10.3

    working_directory: /go/src/github.com/rollout/rox-go

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "go.mod" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: go get -v -t -d ./...

    - run:
        name: Run unit tests
        command: |
          go test -v ./...

    - save_cache:
        key: v1-dependencies-{{ checksum "go.mod" }}
        paths:
        - "/go/pkg"
