version: 2
workflows:
  version: 2
  test:
    jobs:
    - test-1.10
    - test-1.9
jobs:
  test-1.10: &test-template
    docker:
    - image: circleci/golang:1.10.3

    working_directory: /go/src/github.com/rollout/rox-go

    steps:
    - checkout

    - run: go get -v -t -d ./...

    - run:
        name: Run unit tests
        command: |
          go test -v ./...
  test-1.9:
    <<: *test-template
    docker:
    - image: circleci/golang:1.9.7
